- .travis.yml
- cics-bundle-maven-plugin/pom.xml
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEar.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildOsgi.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildWar.java
This adds basic Travis CI support, running a `mvn verify`.
At this point, there are no deployment or publication steps.
> Add builds via Travis CI

- .travis.yml
This adds the property to `mvn` to force it to output colourised text, even when running in batch (non-interactive) mode, to make the output more readable.
> Add colour to Maven build

- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Earbundle.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Osgibundle.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Warbundle.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEar.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildOsgi.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildWar.java
Paths to bundle files aren't generated correctly as the Maven dependency's version is included in the file, but not the bundle part symbolic name.  This updates the bundle part's symbolic name to also include the Maven dependency's version
> Include version number in bundle part symbolic names

- README.md
Now we push snapshots, you don't need to build it yourself.
> Remove old reference to needing to build plugin

- cics-bundle-maven-plugin/src/it/test-reactor-osgi/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-bundle/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-osgi/BundleContent/META-INF/MANIFEST.MF
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-tycho/META-INF/MANIFEST.MF
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-tycho/build.properties
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-tycho/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-osgi/test-tycho/src/main/java/test_tycho/TestEndpoint.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractCICSBundleMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BuildCICSBundleMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Earbundle.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/JavaBasedBundlePart.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Osgibundle.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Warbundle.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildOsgi.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestEarbundle.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestJavaBasedBundlePart.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestOsgibundle.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestWarbundle.java
This pull request is related to #15.
This pull request
- fixes the creation of OSGi bundleparts, by ensuring that the `Bundle-Version` header is correctly from OSGi bundle dependencies' manifests and is set in the OSGi bundlepart's `version` attribute.
- adds tests for bundles using both the bnd-maven-plugin and Tycho.
- improves checking of the `BuildContext` so that, in the IDE, fewer builds will be triggered. For example, an IDE build won't be immediately triggered following a Run Config or command-line `mvn` build.
> Fix OSGi bundlepart creation

- cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/test-bundle/src/main/resources/PROG1.program
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/BundlepartTypeComparator.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/DefineFactory.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/DefineGraph.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BuildCICSBundleMojo.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/bundlegen/BundlepartTypeComparatorTest.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/bundlegen/DefineGraphTest.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildResourcedef.java
This pull request applies a dependency graph to `<define>` elements to avoid users having to order them themselves (or just being ordered in a way that won't work).
The ordering in a cics.xml will be controlled as follows:
- The dependency graph will be used first. Where a bundlepart type depends on another type, the latter will appear before the former.
- Where there's no dependency between resources types, lexicographic ordering of the bundlepart type will be used.
- Within a resource type, lexicographic ordering of the bundlepart name will be used.
This covers just bundlepart types that are currently supported (see README). As we add support for more bundlepart types, we'll need to update the dependency graph.
>  Control the order of <define> elements

- README.md
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/DefineFactory.java
pipeline support isn't complete (see #31) - so disabling for now.
Signed-off-by: Dave Nice <dave@niceweb.org.uk>
> remove pipeline support

- cics-bundle-maven-plugin/pom.xml
call upgrade project license on every build to push a license file into the built Maven plugin.
> generate epl into binaries

- pom.xml
The `nexus-staging-maven-plugin` continues to defer to the `<distributionManagement>` section for snapshot builds.
This pull request restores this section as before, so that it can be used for snapshot builds.
> Restore distributionManagement for snapshots

- cics-bundle-maven-plugin/pom.xml
Having been alerted to a vulnerability by Dependabot, this pull request updates to the later security fix.
> Update dependency to avoid jackson-databind CVEs

- cics-bundle-maven-plugin/src/site/resources/css/site.css
- cics-bundle-maven-plugin/src/site/site.xml
Removes all the modules from the menu to empty it (there's no interesting content anyway), and then uses CSS to hide the empty column (slightly hacky).  Another alternative is probably a custom template that doesn't include the left column at all, but that'd be significantly more work!
Signed-off-by: Stewart Francis <stewartfrancis@uk.ibm.com>
> Hide the leftColumn on the maven site

- _config.yml
gh-pages keeps undoing the theme when it rebuilds because it's not in the master branch
> Set theme jekyll-theme-cayman in master

- README.md
- samples/bundle-reactor-deploy/pom.xml
- samples/bundle-war-deploy/README.md
Reference the samples in the main readme. I've also moved the section about archetypes down, and updated it so that you only have to edit the defaultjvmserver in the pom if you used command line, otherwise you fill it in in the Eclipse dialog. 
> Update doc to reference samples, and move the archetype doc

- README.md
- cics-bundle-maven-plugin/src/it/test-reactor-eba/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-eba/postbuild.bsh
- cics-bundle-maven-plugin/src/it/test-reactor-eba/test-bundle/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-eba/test-eba/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-eba/test-osgi/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-eba/test-osgi/src/main/java/test_osgi/TestEndpoint.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractAutoConfigureBundlePublisherMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractBundlePublisherMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleEbaMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Ebabundle.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/EbabundleTest.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEba.java
Add support for EBA bundle part type including integration test
Build will fail until https://github.com/IBM/cics-bundle-common/pull/16 is fully built
> add eba support

- samples/bundle-reactor-deploy/demo-bundle/pom.xml
- samples/bundle-war-deploy/demo-war/pom.xml
- samples/pom.xml
- samples/src/main/resources/mappings/acceptAll.json
Use wiremock to accept deployment request and return 200.
This has limitations - we only detect issues that are validated client-side because we don't actually get as far as the server.
> use wiremock to test samples

- cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/pom.xml
- cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/src/main/java/com/example/servlet/HelloServlet.java
- cics-bundle-maven-plugin/src/it/setup-test-war/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-deploy-insecure/postbuild.groovy
- cics-bundle-maven-plugin/src/it/test-bundle-ear/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-eba/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-war/pom.xml
- cics-bundle-maven-plugin/src/it/test-reactor-eba/test-osgi/pom.xml
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/BundleValidator.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEar.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEba.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildOsgi.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildResourcedef.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildWar.java
- cics-bundle-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/pom.xml
- cics-bundle-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/src/main/java/com/example/servlet/HelloServlet.java
This pull requests adds reference to JCICS from the archetypes, to make it clearer how to do that.
I also found that the integration tests were unreliable for me, and I think it was because of the change of JRE. I've altered them to be more resilient to that sort of change, by doing XML-style comparison and another couple of changes.
I've also reduced the number of warnings emitted by the integration tests by giving plugins explicit version numbers.
> JCICS in archetypes

- samples/bundle-reactor-deploy/demo-war/pom.xml
So users don't get a warning when using the sample
> Added version to maven-compiler-plugin 

- README.md
IBM Knowledge Center is replaced by IBM Docs.
> Change reference to KC to IBM Docs

- .github/workflows/codeql-analysis.yml
- .travis.yml
- .travis/script.sh
- .travis/setup-signing.sh
- README.md
This changes build and other references to the `master` branch to use `main` instead.
> Rename master to main

- cics-bundle-maven-plugin/pom.xml
- pom.xml
maven-deploy-plugin and maven-install-plugin were agreed with Stew to be left at 3.0.0-M1 as that looks to be a major milestone/release
> Downgraded some of the plugins from milestones to releases

- .github/workflows/maven-build.yml
- .github/workflows/maven-scheduled-build.yml
We temporarily used an alternative action to allow GPG subkeys when signing.
actions/setup-java#226 merged and we can revert to the original.
> Revert to mainline GitHub action because actions/setup-java#226 merged

- cics-bundle-maven-plugin/src/it/test-repeat-bundle-war/invoker.properties
- cics-bundle-maven-plugin/src/it/test-repeat-bundle-war/pom.xml
- cics-bundle-maven-plugin/src/it/test-repeat-bundle-war/src/main/java/test_war/TestEndpoint.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractBundleJavaMojo.java
If the single-module mojos (any that inherit `AbstractBundleJavaMojo`) are run more than once without cleaning, they fail to overwrite existing files in the working directory.
Fixes #191.
First commit has a test and should fail... second commit has the fix.
> Remove working directory when running single-module mojos

- cics-bundle-maven-plugin/pom.xml
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractBundlePublisherMojo.java
- pom.xml
- samples/pom.xml
Updated dependencies. We were setting a bundleRelease incorrectly to a build version, when it should always be set to 0, and thats now fixed in common so we have fixed it here as well as we no longer need to provide a build number
> Updated dependencies

- .github/workflows/maven-build.yml
Wait for #219.
This fixes a warning we see in the workflow that deploys to GitHub Pages - the step 'deployment' is referenced but not declared.
> Fix URL for GitHub Pages environment deployment

- cics-bundle-maven-plugin/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-war-final-name/pom.xml
- cics-bundle-maven-plugin/src/it/test-bundle-war-final-name/postbuild.bsh
- cics-bundle-maven-plugin/src/it/test-bundle-war-final-name/src/main/java/test_war/TestEndpoint.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractBundleJavaMojo.java
- cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/PackageCICSBundleMojo.java
- cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildTestBundleWarFinalName.java
Fixes #224 
Note that the bundle is now created without a version, as verified by `test-bundle-war-final-name`.  Internally within the bundle zip, the resulting war file will still have a version.
Note that if you're using the `deploy` goal with the bundle deploy API, the resulting bundle directory will still have the version number in, as it's derived from the version in the manifest within the bundle file, not the bundle file name.
This is still useful for scenarios where you're deploying the resulting bundle file yourself though
> Use project.build.finalName to derive artifact name

- README.md
- cics-bundle-deploy-reactor-archetype/pom.xml
- cics-bundle-maven-plugin/pom.xml
- cics-bundle-maven-plugin/src/main/resources/META-INF/plexus/components.xml
- cics-bundle-maven-site/pom.xml
- cics-bundle-reactor-archetype/pom.xml
- pom.xml
- samples/pom.xml
In Maven Bundle Plugin version 2.0.0 we moved the binding of the build goal from the compile phase to the package phase
https://github.com/IBM/cics-bundle-maven/issues/197
> build goal moved to package and major version update

- README.md
- pom.xml
- samples/bundle-reactor-deploy/pom.xml
This updates the endpoints to use the newer Portal OSSRH Staging API.
Because we're already using the Nexus deploy plugin, we don't need to do additional API calls, so this should be sufficient.
Once this is merged, the build _should_ fail with an authentication error. I'll then switch out the API key for one that works with the new publishing portal, and then re-run, at which point it should succeed.
> Update endpoints to migrate to Portal OSSRH Staging API

- .github/workflows/codeql-analysis.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-scheduled-build.yml
- README.md
- cics-bundle-maven-plugin/pom.xml
- pom.xml
- samples/bundle-reactor-deploy/pom.xml
Takes all changes from `main` that don't relate to the breaking 2.x change, allowing us to release a 1.x version without.
It may also be helpful for reviewers to check that 1.x branched off at the appropriate point.
> 1.x plus cherry pick
