IBM/cics-bundle-maven

README.md

Add README content for how to use the plugin, plus the supported bundlepart types.

Add README content for how to use the plugin

---

README.md

Also add xml formatting hints
Signed-off-by: Stewart Francis <stewartfrancis@uk.ibm.com>

Update readme with info about consuming snapshot builds

---

cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundlePart.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/JavaBasedBundlePart.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestEarbundle.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestJavaBasedBundlePart.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestOsgibundle.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/TestWarbundle.java

Signed-off-by: Dave Nice <dave@niceweb.org.uk>

add unit tests

---

README.md
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/pom.xml
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/postbuild.bsh
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/test-bundle/pom.xml
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/test-bundle/src/main/resources/EventBinding.evbind
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/test-bundle/src/main/resources/mymap.urimap
cics-bundle-maven-plugin/src/it/test-reactor-resourcedef/test-bundle/src/main/resources/noextension
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/BundleConstants.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/Define.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/bundlegen/DefineFactory.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractCICSBundleMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BuildCICSBundleMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundlePart.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Earbundle.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/JavaBasedBundlePart.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Osgibundle.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/Warbundle.java
cics-bundle-maven-plugin/src/main/resources/META-INF/plexus/components.xml
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildResourcedef.java

this pull request is related to issue #14
create cics.xml defines for some supported bundle part types
use a map to track which bundle parts are supported
some refactoring of code to try and keep things tidy.

copy bundle parts across

---

cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/PackageCICSBundleMojo.java
cics-bundle-maven-plugin/src/main/resources/META-INF/plexus/components.xml
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildEar.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildOsgi.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildResourcedef.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildWar.java

Make plugin emit zip files instead of cics-bundle files

---

cics-bundle-maven-plugin/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml

Signed-off-by: Dave Nice <dave@niceweb.org.uk>

release for 0.0.1

---

cics-bundle-deploy-reactor-archetype/README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-deploy-reactor-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-bundle/pom.xml
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-bundle/settings.xml
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/pom.xml
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/src/main/java/com/example/servlet/HelloServlet.java
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/__rootArtifactId__-war/src/main/webapp/index.html
cics-bundle-deploy-reactor-archetype/src/main/resources/archetype-resources/pom.xml
pom.xml

Archetype for building and deploying a bundle

---

.travis/script.sh

Temporarily pause building the site while I consider the lack of credentials :)

don't build site

---

.travis/script.sh
pom.xml

Link scm-plugin call with credentials in settings.xml.

add serverId for github server

---

pom.xml

Last attempt - I can see a wrong password makes my local build fail and a right password has it pass.

trying setting user/pass directly

---

README.md

Signed-off-by: Stewart Francis <stewartfrancis@uk.ibm.com>

Build and maven central badges in the readme

---

cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java
pom.xml

Add maven doc for deploy mojo
publish doc to main IBM repo rather than davenice

Add deploy doc, publish doc to main repo

---

.travis/script.sh
README.md
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BuildCICSBundleMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleEarMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleOSGiMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleWarMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/PackageCICSBundleMojo.java
cics-bundle-maven-site/pom.xml
pom.xml

I've added words that try and make it clearer when you'd want to use the 'standard' build Mojo in a separate module, or use bundle-ear etc.
Please do edit for clarity during the review!

Improve clarity around different mojos

---

.travis/script.sh
README.md
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
pom.xml

Copy readme into gh-pages branch and include link to the maven doc.

Add readme with link to Maven doc

---

cics-bundle-maven-site/pom.xml

Previous commit didn't include the images folder itself

---

.travis.yml
.travis/script.sh
pom.xml
travis-settings.xml

push from travis instead of the pom to stop accidentally publishes.
Signed-off-by: Dave Nice <dave.nice@uk.ibm.com>

push from travis

---

cics-bundle-maven-site/pom.xml

Include the config file in the gh-pages branch

---

README.md
cics-bundle-maven-site/pom.xml
samples/bundle-reactor-deploy/README.md
samples/bundle-war-deploy/README.md

Add links to the source and readmes of samples so they can be linked from github.io

Add links to doc for samples

---

pom.xml
samples/bundle-reactor-deploy/demo-bundle/pom.xml
samples/bundle-war-deploy/demo-war/pom.xml
samples/pom.xml

Initially build the samples (but stop before the deploy point because we don't have a wiremock server in yet)

build samples

---

README.md

Use the deploy archetype as the example, remove snippet 

Updates to archetype doc

---

README.md

Add prerequisites 

---

cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java

Add lightweight log message detailing where we're deploying to.
Signed-off-by: Dave Nice <dave.nice@uk.ibm.com>

log message when deploying

---

ARCHETYPES-README.md
README.md
cics-bundle-maven-site/pom.xml

Pull archetype doc out to separate page

---

README.md

Extend doc to cover deploy steps

---

cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java

Signed-off-by: Dave Nice <dave.nice@uk.ibm.com>

be careful about how URL is described

---

README.md
samples/bundle-reactor-deploy/README.md
samples/bundle-war-deploy/README.md

Updated doc for clarity. (Hopefully _greater_ clarity)

link to beta KC doc, various updates

---

README.md
cics-bundle-maven-plugin/src/it/test-bundle-eba/pom.xml
cics-bundle-maven-plugin/src/it/test-bundle-eba/postbuild.bsh
cics-bundle-maven-plugin/src/it/test-bundle-eba/test-osgi/pom.xml
cics-bundle-maven-plugin/src/it/test-bundle-eba/test-osgi/src/main/java/test_osgi/TestEndpoint.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildTestBundleEba.java

Add integration test for EBA bundles

---

cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/invoker.properties
cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/pom.xml
cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/postbuild.groovy
cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/prebuild.bsh
cics-bundle-maven-plugin/src/it/test-bundle-war-deploy-userprops/src/main/java/test_war/TestEndpoint.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractAutoConfigureBundlePublisherMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractBundleJavaMojo.java
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/PackageCICSBundleMojo.java

Broad (but not quite exhaustive) coverage of user properties

Integration tests for user properties

---

README.md
samples/bundle-reactor-deploy/demo-bundle/pom.xml
samples/bundle-war-deploy/README.md
samples/bundle-war-deploy/demo-war/pom.xml

Signed-off-by: Vera <vera.xx.c@me.com>

change default jvm server name to DFHWLP

---

.gitignore
cics-bundle-maven-plugin/pom.xml

Signed-off-by: Steve Bolton <boltonst@uk.ibm.com>

ASoC scan - Ignore scan folder, move deps to later versions

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/pom.xml

Back to development SNAPSHOTs

---

README.md
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/pom.xml
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/postbuild.bsh
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/pom.xml
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/bundleParts/EventBindingWrongDir.evbind
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/bundleParts/PROG1WrongDir.program
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/bundleParts/mymapWrongDir.urimap
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/bundleParts/noextensionWrongDir
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/differentDirectory/EventBinding.evbind
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/differentDirectory/PROG1.program
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/differentDirectory/mymap.urimap
cics-bundle-maven-plugin/src/it/test-reactor-bundlePartDirectory/test-bundle/src/main/differentDirectory/noextension
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/AbstractAutoConfigureBundlePublisherMojo.java
cics-bundle-maven-plugin/src/test/java/com/ibm/cics/cbmp/PostBuildBundlePartDirectory.java

Signed-off-by: Sophie Green <sophiegr@uk.ibm.com>

Allow bundle parts directory to be configurable and add integration test

---

ARCHETYPES-README.md
README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/bundle-reactor-deploy/demo-bundle/pom.xml
samples/bundle-war-deploy/README.md
samples/bundle-war-deploy/demo-war/pom.xml
samples/pom.xml

Release1.0.2

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml

Back to dev snapshots

---

samples/pom.xml

Attempt to fix broken travis build

---

cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java

Signed-off-by: Sophie Green <sophiegr@uk.ibm.com>

Remove validation for cicsplex and region - this will happen server side

---

README.md

TOC update was missed by #166.

Update TOC for support statement

---

cics-bundle-maven-plugin/pom.xml

Bump cics-bundle-common to 1.0.3-SNAPSHOT

Bump cics-bundle-common to 1.0.3-SNAPSHOT

---

.github/workflows/maven-scheduled-build.yml
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java

Add checks to make sure both or neither of cicsplex and region are set

---

.github/workflows/maven-scheduled-build.yml

Fix cron syntax

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/bundle-reactor-deploy/demo-war/pom.xml
samples/bundle-war-deploy/demo-war/pom.xml
samples/pom.xml

Updates plugins and dependencies to latest

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml

Dev commit for 1.0.4-SNAPSHOT

---

samples/pom.xml

To fix the push to sonatype snapshots

Update the sample project version

---

README.md

Signed-off-by: Vera <vera.xx.c@me.com>
Hi @tom-foyle , I created this PR to add the SMSSJ troubleshooting info, using similar wording to that of the Gradle plugin repo. Could you take a look? Thanks.

add troubleshooting content, also fixed a typo

---

README.md

Fixes #200 
Signed-off-by: Vera Chan <vera.xx.c@me.com>

add a note about EBA stabilization

---

README.md

Fixes same issue as IBM/cics-bundle-gradle#123

Replace RFE link with Idea site

---

README.md

Related to #203 
Signed-off-by: Kye Maloy <kye.maloy@ibm.com>

Updated README with some mvn commands for context for new users

---

cics-bundle-maven-plugin/pom.xml

Update guava to latest version

Update version of guava

---

.pre-commit-config.yaml
.secrets.baseline

Added Detect Secrets config file and pre-commit script.
Signed-off-by: Enam Khan enam.khan@uk.ibm.com

Added Detect Secrets config

---

README.md
cics-bundle-maven-plugin/src/main/java/com/ibm/cics/cbmp/BundleDeployMojo.java

Resolves https://github.com/IBM/cics-bundle-maven/issues/151
1.Added filename with the log of deployment
2.added<classifier>cics-bundle</classifier> as mandatory in troubleshooting if someone is facing issue in deploy

classifier fix issue

---

cics-bundle-maven-plugin/pom.xml

Update Maven plugins

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml

Signed-off-by: Samarin-Nayak Samreen.Nayak@ibm.com

add-Description-and-license

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/pom.xml

Release 1.0.6 of the Maven plugin with latest common version 2.0.1

Release 1.0.6.

---

cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/pom.xml

Update version to 1.0.7-SNAPSHOT for further development

update version to 1.0.7-SNAPSHOT

---

README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/pom.xml

Release 1.0.7

---

ARCHETYPES-README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/bundle-reactor-deploy/demo-bundle/pom.xml
samples/bundle-war-deploy/README.md
samples/bundle-war-deploy/demo-war/pom.xml
samples/pom.xml

Depends on #248 and releasing it to Maven Central.

Prepare for development of 1.0.8-SNAPSHOT

---

README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/pom.xml

Does exactly what it says in the title.

Release 1.0.8

---

ARCHETYPES-README.md
README.md
cics-bundle-deploy-reactor-archetype/pom.xml
cics-bundle-maven-plugin/pom.xml
cics-bundle-maven-site/pom.xml
cics-bundle-reactor-archetype/pom.xml
pom.xml
samples/bundle-reactor-deploy/demo-bundle/pom.xml
samples/bundle-war-deploy/README.md
samples/bundle-war-deploy/demo-war/pom.xml
samples/pom.xml

Ups the version numbers to release 2.0.0.
Also fixes a couple of links in the readme that haven't aged well.

Release 2.0.0
